version: v1
resources:
- name: app-deployment
  driver: helm
  source:
    kind: local
    path: ./examples/helm/local/example-chart
  target:
    kind: local
    namespace: alexander
    name: local-dummy
  config: